package daemon

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/thehenrymcintosh/ship/internal/agent"
	"github.com/thehenrymcintosh/ship/internal/checkin"
	"github.com/thehenrymcintosh/ship/internal/engine/steps"
	"github.com/thehenrymcintosh/ship/internal/pipeline"
	"github.com/thehenrymcintosh/ship/internal/store"
	gitws "github.com/thehenrymcintosh/ship/internal/workspace/git"
)

// CardView is a check-in or needs-attention card: one layout for all of
// them, most important first. The web card, the inbox row and the CLI all
// render it.
type CardView struct {
	Kind     checkin.Kind `json:"kind"`
	Label    string       `json:"label"`
	Pipeline string       `json:"pipeline"`
	From     string       `json:"from,omitempty"` // the step it came from
	Since    time.Time    `json:"since"`
	CostUSD  float64      `json:"cost_usd"`
	// Headline says in one line what's being decided (or what broke);
	// Question is the check-in's own question when the headline isn't it.
	Headline  string `json:"headline"`
	Question  string `json:"question,omitempty"`
	Situation string `json:"situation,omitempty"`
	// Source is where the headline came from: diagnosis, agent, summary
	// (generated by SummaryModel) or question.
	Source       string `json:"source"`
	SummaryModel string `json:"summary_model,omitempty"`
	// Recommended is the recommended choice, with Reason; Fix is the
	// recommended fix of a diagnosed problem (and takes precedence).
	Recommended string       `json:"recommended,omitempty"`
	Reason      string       `json:"reason,omitempty"`
	Fix         *checkin.Fix `json:"fix,omitempty"`
	// FixFile and FixWrite say what a fix that edits the pipeline will
	// write, and where, before it does.
	FixFile  string       `json:"fix_file,omitempty"`
	FixWrite string       `json:"fix_write,omitempty"`
	FixStep  string       `json:"fix_step,omitempty"` // the step a fix retries
	FixErr   string       `json:"fix_error,omitempty"`
	Tests    []string     `json:"tests,omitempty"`
	ResetsAt time.Time    `json:"resets_at,omitempty"`
	Options  []ChoiceView `json:"options,omitempty"`
	// DoRecommended is set when the recommended choice can be sent as is
	// (no note required).
	DoRecommended bool `json:"do_recommended,omitempty"`
	// What the viewer compares with what they saw last time.
	Seen SeenView `json:"seen"`
}

// SeenView is what a run looks like now, for "since you last looked".
type SeenView struct {
	Visits  int            `json:"visits"`
	Commits int            `json:"commits"` // -1 when unknown
	Steps   map[string]int `json:"steps"`   // visits per step
}

// JSON is the view as a JSON attribute value.
func (v SeenView) JSON() string {
	b, _ := json.Marshal(v)
	return string(b)
}

// commits counts commits from the run's base to its head (the head the
// latest visit started from), cached by the pair.
var commitCache sync.Map

func runCommits(s *store.RunSnapshot) int {
	if s.Workspace == nil || s.Workspace.BaseSHA == "" {
		return -1
	}
	head := ""
	for i := len(s.Visits) - 1; i >= 0 && head == ""; i-- {
		head = s.Visits[i].HeadSHA
	}
	if head == "" {
		return 0
	}
	key := s.Repo + "\x00" + s.Workspace.BaseSHA + ".." + head
	if n, ok := commitCache.Load(key); ok {
		return n.(int)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	out, err := gitws.Git(ctx, s.Repo, "rev-list", "--count", s.Workspace.BaseSHA+".."+head)
	if err != nil {
		return -1
	}
	n, err := strconv.Atoi(strings.TrimSpace(out))
	if err != nil {
		return -1
	}
	commitCache.Store(key, n)
	return n
}

func seenView(s *store.RunSnapshot) SeenView {
	v := SeenView{Visits: len(s.Visits), Commits: runCommits(s), Steps: map[string]int{}}
	for _, vs := range s.Visits {
		v.Steps[vs.Step]++
	}
	return v
}

// readDenials reads a visit's raw permission denials.
func readDenials(visitDir string) []json.RawMessage {
	b, err := os.ReadFile(filepath.Join(visitDir, "result.json"))
	if err != nil {
		return nil
	}
	var r struct {
		Denials []json.RawMessage `json:"permission_denials"`
	}
	_ = json.Unmarshal(b, &r)
	return r.Denials
}

// card builds the check-in card of a run waiting for a person, or nil.
func (d *Daemon) card(v *RunView) *CardView {
	s := v.S
	kind := checkin.Classify(s)
	if kind == "" {
		return nil
	}
	c := &CardView{Kind: kind, Label: kind.Label(), Pipeline: s.Pipeline, CostUSD: s.CostUSD, Options: v.Choices, Seen: v.Seen}
	dir := d.st.RunDir(s.ID)
	visitDir := func(vs *store.VisitSummary) string { return filepath.Join(dir, store.VisitsDir, vs.Dir) }

	var bad *store.VisitSummary // the visit to diagnose
	if pa := s.PendingAsk; pa != nil {
		c.Since, c.Headline, c.Source = pa.Since, pa.Question, "question"
		if av := s.Visit(pa.Seq); av != nil {
			c.From = av.Step
		}
		if pa.Kind == store.AskKindAsk {
			if pv := checkin.Before(s, pa.Seq); pv != nil {
				c.From = pv.Step
				if checkin.Failed(pv) {
					bad = pv
				} else if dec := steps.ReadDecision(visitDir(pv)); dec != nil {
					c.applyDecision(dec.Headline, dec.Situation, dec.Recommended, dec.Reason, dec.Options)
					c.Source = "agent"
				} else if av := s.Visit(pa.Seq); av != nil {
					if sum := steps.ReadCheckInSummary(visitDir(av)); sum != nil {
						c.applyDecision(sum.Headline, sum.Situation, sum.Recommended, sum.Reason, sum.Options)
						c.Source, c.SummaryModel = "summary", sum.Model
					}
				}
			}
			c.DoRecommended = c.Recommended != "" && pa.Input != "required"
		}
		if pa.Kind == store.AskKindSplitReview {
			c.Situation = fmt.Sprintf("%d slices proposed. Read their titles and acceptance criteria below, then approve, or re-split with a note saying what to change.", len(s.ProposedSlices))
		}
	} else {
		c.Since = s.UpdatedAt
		bad = s.LastVisit()
		if bad != nil {
			c.From = bad.Step
		}
		c.Headline, c.Source = s.StatusReason, "question"
	}
	if bad != nil || s.Status == store.StatusNeedsAttention {
		in := checkin.Input{Snap: s, Visit: bad, BudgetUSD: v.Budget.USD, BudgetTokens: v.Budget.Tokens}
		if bad != nil {
			in.Denials = readDenials(visitDir(bad))
			if bad.Type == pipeline.TypeRun {
				in.Output = readTail(filepath.Join(visitDir(bad), "stdout.log"), 64<<10) + "\n" + readTail(filepath.Join(visitDir(bad), "stderr.log"), 16<<10)
			}
			if v.P != nil && v.P.Steps[bad.Step] != nil {
				in.Timeout = v.P.Timeout(v.P.Steps[bad.Step])
			}
		}
		if w := d.usageView().Short(); w != nil {
			in.LimitResets = w.ResetsAt
		}
		if dg := checkin.Diagnose(in); dg != nil {
			if c.Source == "question" && c.Headline != dg.Headline {
				c.Question = c.Headline
			}
			c.Kind, c.Label = checkin.Problem, checkin.Problem.Label()
			c.Headline, c.Situation, c.Source = dg.Headline, dg.Explain, "diagnosis"
			c.Tests, c.ResetsAt, c.Fix = dg.Tests, dg.ResetsAt, dg.Fix
			c.Recommended, c.Reason, c.DoRecommended = "", "", false
			if bad != nil {
				c.FixStep = bad.Step
			}
			d.planCardFix(c, s)
		}
	}
	if c.Source == "question" {
		c.Question = ""
	}
	for i := range c.Options {
		c.Options[i].Recommended = c.Options[i].Label == c.Recommended
	}
	return c
}

func (c *CardView) applyDecision(headline, situation, rec, reason string, opts []agent.DecisionOption) {
	if c.Headline != headline {
		c.Question = c.Headline
	}
	c.Headline, c.Situation, c.Recommended, c.Reason = headline, situation, rec, reason
	for _, o := range opts {
		for i := range c.Options {
			if c.Options[i].Label == o.Choice {
				c.Options[i].Consequence = o.Consequence
			}
		}
	}
}

// planCardFix fills in what a pipeline-editing fix will write.
func (d *Daemon) planCardFix(c *CardView, s *store.RunSnapshot) {
	if c.Fix == nil || (c.Fix.Kind != checkin.FixAllowTool && c.Fix.Kind != checkin.FixTimeout) {
		return
	}
	p, err := d.planFix(s, c.Fix.Kind, c.FixStep, c.Fix.Value)
	if err != nil {
		c.FixErr = err.Error()
		return
	}
	c.FixFile, c.FixWrite = p.display, p.snippet
}

// fixPlan is a pipeline edit a fix makes.
type fixPlan struct {
	file    string // absolute
	display string // relative to the repo when inside it
	path    []string
	value   any
	snippet string // the YAML it writes, for the confirmation
	step    string // the step to retry afterwards
}

// planFix works out where an allow-tool or timeout fix writes, for the
// run's pipeline as it is in the repo now.
func (d *Daemon) planFix(s *store.RunSnapshot, kind, step, value string) (*fixPlan, error) {
	loader := d.eng.Loader(s.Repo)
	file := loader.Path(s.Pipeline)
	if file == "" {
		return nil, fmt.Errorf("can't find the %s pipeline's file", s.Pipeline)
	}
	f, findings := loader.Load(s.Pipeline)
	if f == nil {
		msg := "can't load the pipeline"
		if len(findings) > 0 {
			msg = findings[0].String()
		}
		return nil, fmt.Errorf("%s", msg)
	}
	st := f.Pipeline.Steps[step]
	if st == nil {
		return nil, fmt.Errorf("the %s pipeline has no step %q now", s.Pipeline, step)
	}
	p := &fixPlan{file: file, display: file, step: step}
	if rel, err := filepath.Rel(s.Repo, file); err == nil && !strings.HasPrefix(rel, "..") {
		p.display = rel
	}
	switch kind {
	case checkin.FixAllowTool:
		cfg, err := d.eng.Config(s.Repo)
		if err != nil {
			return nil, err
		}
		tools := slices.Clone(f.Pipeline.AgentFor(cfg.Agent, st).AllowedTools)
		added := false
		for _, t := range strings.Fields(strings.ReplaceAll(value, "\n", " ")) {
			if t != "" && !slices.Contains(tools, t) {
				tools, added = append(tools, t), true
			}
		}
		if !added {
			return nil, fmt.Errorf("%s already allows %s", step, value)
		}
		p.path, p.value = []string{"agent", "allowed_tools"}, tools
		if st.AllowedTools != nil {
			// The step's own list replaces the pipeline's, so it goes there.
			p.path = []string{"steps", step, "allowed_tools"}
		}
		p.snippet = yamlSnippet(p.path, "["+strings.Join(tools, ", ")+"]")
	case checkin.FixTimeout:
		if _, err := pipeline.ParseDuration(value); err != nil {
			return nil, err
		}
		p.path, p.value = []string{"steps", step, "timeout"}, value
		p.snippet = yamlSnippet(p.path, value)
	default:
		return nil, fmt.Errorf("unknown fix %q", kind)
	}
	return p, nil
}

func yamlSnippet(path []string, value string) string {
	var b strings.Builder
	for i, k := range path {
		b.WriteString(strings.Repeat("  ", i) + k + ":")
		if i == len(path)-1 {
			b.WriteString(" " + value)
		}
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n")
}

// FixBody is POST /api/runs/{id}/fix.
type FixBody struct {
	Kind  string `json:"kind"`
	Step  string `json:"step"`
	Value string `json:"value"`
}

// fix applies an allow-tool or timeout fix: it edits the pipeline file,
// then moves the run onto the edited pipeline at the step, which runs again.
func (d *Daemon) fix(w http.ResponseWriter, r *http.Request) {
	id, ok := d.resolve(w, r)
	if !ok {
		return
	}
	var b FixBody
	if err := decode(r, &b); err != nil {
		writeErr(w, 400, "bad_request", err.Error())
		return
	}
	s, err := d.eng.Snapshot(id)
	if err != nil {
		writeEngineErr(w, err)
		return
	}
	if !s.Status.InInbox() {
		writeErr(w, 409, "conflict", "the run isn't waiting for you")
		return
	}
	p, err := d.planFix(s, b.Kind, b.Step, b.Value)
	if err != nil {
		writeErr(w, 422, "invalid", err.Error())
		return
	}
	data, err := os.ReadFile(p.file)
	if err != nil {
		writeErr(w, 500, "internal", err.Error())
		return
	}
	out, err := pipeline.SetYAML(data, p.path, p.value)
	if err != nil {
		writeErr(w, 422, "invalid", fmt.Sprintf("can't edit %s: %v", p.display, err))
		return
	}
	mode := os.FileMode(0o644)
	if fi, err := os.Stat(p.file); err == nil {
		mode = fi.Mode().Perm()
	}
	if err := store.WriteFileAtomic(p.file, out, mode); err != nil {
		writeErr(w, 500, "internal", err.Error())
		return
	}
	src := "ui"
	if r.Header.Get("X-Ship-Client") == "cli" {
		src = "cli"
	}
	if _, err := d.eng.Upgrade(r.Context(), id, p.step, src); err != nil {
		writeEngineErr(w, err)
		return
	}
	time.Sleep(30 * time.Millisecond)
	if r.Header.Get("HX-Request") == "true" {
		w.Header().Set("HX-Trigger", "ship-refresh")
	}
	snap, err := d.eng.Snapshot(id)
	if err != nil {
		writeEngineErr(w, err)
		return
	}
	writeJSON(w, 200, snap)
}

// getCard is GET /api/runs/{id}/card: the check-in card (null when the run
// isn't waiting for anyone).
func (d *Daemon) getCard(w http.ResponseWriter, r *http.Request) {
	id, ok := d.resolve(w, r)
	if !ok {
		return
	}
	v, err := d.runView(id)
	if err != nil {
		writeEngineErr(w, err)
		return
	}
	writeJSON(w, 200, v.Card)
}
